---
- name: newrelic | overlay new relic configuration
  template: src='nrsysmond.cfg.j2' dest='/etc/newrelic/nrsysmond.cfg' owner='newrelic' group='newrelic' mode='0640'

- name: newrelic | start service and enable on boot
  service: name='newrelic-sysmond' state='restarted' enabled='yes'
  ignore_errors: yes
